
User.new(name: "Josh",
         email: "josh@gmail.com",
         password: "qweqwe",
         password_confirmation: "qweqwe").save(validate: false)
puts "User Josh created!"

User.new(name: "Natalie",
         email: "natalie@gmail.com",
         password: "qweqwe",
         password_confirmation: "qweqwe").save(validate: false)
puts "User Natalie created!"

User.new(name: "Admin",
         email: 'admin@gmail.com',
         password: 'qweqwe',
         password_confirmation: 'qweqwe',
         admin: true).save(validate: false)
puts "Admin created!"

male_names =
  [["Aaron",
    "From the Hebrew name ('Aharon) which is most likely of unknown Egyptian origin. Other theories claim a Hebrew derivation, and suggest meanings such as 'high mountain' or 'exalted'. In the Old Testament this name is borne by the older brother of Moses. He acted as a spokesman for his brother when they appealed to the pharaoh to release the Israelites from slavery. Aaron's rod produced miracles and plagues to intimidate the pharaoh. After the departure from Egypt and arrival at Mount Sinai, God installed Aaron as the first high priest of the Israelites and promised that his descendants would form the priesthood. As an English name, Aaron has been in use since the Protestant Reformation. This name was borne by the American politician Aaron Burr (1756-1836), notable for killing Alexander Hamilton in a duel.",
    "Arron, Aaren (English), Aharon (Hebrew)",
    "AIR-en (English)",
    52],
    ["Adrian",
    "Form of Hadrianus. Several saints and six popes have borne this name, including the only English pope, Adrian IV, and the only Dutch pope, Adrian VI. As an English name, it has been in use since the Middle Ages, though it was not popular until modern times.",
    "Hadrianus (Ancient Roman), Adrià (Catalan), Adrijan, Jadran, Jadranko (Croatian), Adriaan, Arjan, Adrianus, Arie, Aris (Dutch), Adrien, Hadrien (French), Hadrian (History), Adorján, Adrián (Hungarian), Adriano (Italian), Ad (Limburgish), Adrijan (Macedonian), Adriano (Portuguese), Jadran, Jadranko (Serbian), Jadran, Jadranko (Slovene), Adrián (Spanish)",
    "AY-dree-ən (English), AHD-ryahn (Polish), AH-dree-ahn (German), ah-dree-AHN (Russian)",
    58],
    ["Aidan",
    "Anglicized form of AODHÁN. In the latter part of the 20th century it became popular in America due to its sound, since it uses the same fashionable aden suffix sound found in such names as Braden and Hayden.",
    "Aodhán, Edan (Irish), Aodhán, Edan (Scottish), Aden, Aiden, Aydan, Ayden (English)",
    "AY-den",
    185],
    ["Alexander",
    "Latinized form of the Greek name (Alexandros), which meant 'defending men' from Greek (alexo) 'to defend, help' and (aner) 'man'. In Greek mythology this was another name of the hero Paris, and it also belongs to several characters in the New Testament. However, the most famous bearer was Alexander the Great, King of Macedon. In the 4th century BC he built a huge empire out of Greece, Egypt, Persia, and parts of India. Due to his fame, and later medieval tales involving him, use of his name spread throughout Europe.",
    "Aleksander (Norwegian), Aleksander (Danish), Alexandros (Ancient Greek), Alexandros (Greek Mythology)",
    "a-lig-ZAN-der (English), ah-lek-SAHN-der (German), AW-lek-sawn-der (Hungarian)",
    8],
    ["Andrew",
    "English form of the Greek name (Andreas), which was derived from (andreios) 'manly, masculine', a derivative of (aner) 'man'. In the New Testament the apostle Andrew, the first disciple to join Jesus, is the brother of Simon Peter. According to tradition, he later preached in the Black Sea region, with some legends saying he was crucified on an X-shaped cross. Andrew, being a Greek name, was probably only a nickname or a translation of his real Hebrew name, which is not known. This name has been common (in various spellings) throughout the Christian world, and it became very popular in the Middle Ages. Saint Andrew is regarded as the patron of Scotland, Russia, Greece and Romania. The name has been borne by three kings of Hungary, American president Andrew Jackson (1767-1845), and, more recently, English composer Andrew Lloyd Webber (1948-).",
    "Andre, Andreas, Andie, Andy, Drew",
    "AN-droo (English)",
    30],
    ["Anthony",
    "English form of the Roman family name Antonius, which is of unknown Etruscan origin. The most notable member of the Roman family was the general Marcus Antonius (called Mark Antony in English), who for a period in the 1st century BC ruled the Roman Empire jointly with Augustus. When their relationship turned sour, he and his mistress Cleopatra were attacked and forced to commit suicide, as related in Shakespeare's tragedy 'Antony and Cleopatra' (1606). The name became regularly used in the Christian world due to the fame of Saint Anthony the Great, a 4th-century Egyptian hermit who founded Christian monasticism. Its popularity was reinforced in the Middle Ages by the 13th-century Saint Anthony of Padua, the patron saint of Portugal. It has been commonly (but incorrectly) associated with Greek ανθος (anthos) 'flower', which resulted in the addition of the h to this spelling in the 17th century.",
    "Antony, Tony, Antonia",
    "AN-tha-nee, AN-ta-nee",
    25],
    ["Arnold",
    "From a Germanic name meaning 'eagle power', derived from the elements arn 'eagle' and wald 'power'. The Normans brought it to England, where it replaced the Old English cognate Earnweald. It died out as an English name after the Middle Ages, but it was revived in the 19th century.Saints bearing the name include an 8th-century musician in the court of Charlemagne and an 11th-century French bishop who is the patron saint of brewers. It was also borne by Arnold of Brescia, a 12th-century Augustinian monk who rebelled against the church and was eventually hanged. Famous modern bearers include American golfer Arnold Palmer (1929-) and Austrian-American actor and politician Arnold Schwarzenegger (1947-).",
    "Arn, Arnie (English), Arndt, Arne, Arno (German), Arnau (Catalan), Arnoud, Arnout, Aart, Arend, Arno (Dutch), Arnaud (French), Ane, Anne, Arke (Frisian), Arnaldo (Italian), Nöl, Nölke (Limburgish), Arnt (Norwegian)",
    "AHR-neld (English), AHR-nawlt (German)",
    357],
    ["Austin",
    "Medieval contracted form of AUGUSTINE (1). Modern use of the name is probably also partly inspired by the common surname Austin, which is of the same origin. This is also the name of a city in Texas.",
    "Augustine, Austen, Austyn",
    "AWS-tin",
    69],
    ["Baldwin",
    "Derived from the Germanic elements bald 'bold, brave' and win 'friend'. In the Middle Ages this was a popular name in Flanders and among the Normans, who brought it to Britain. It was borne by one of the leaders of the First Crusade, an 11th-century nobleman from Flanders. After the crusaders conquered Jerusalem, he was crowned as the king of the Kingdom of Jerusalem.",
    "Boudewijn, Boele (Dutch), Baudouin (French), Baldovino, Baldo (Italian), Balduíno (Portuguese), Balduino, Baldo (Spanish), Maldwyn (Welsh)",
    "BAWLD-win (English)",
    680],
    ["Benedict",
    "From the Late Latin name Benedictus which meant 'blessed'. Saint Benedict was an Italian monk who founded the Benedictines in the 6th century. After his time the name was common among Christians, being used by 16 popes. In England it did not come into use until the 12th century, at which point it became very popular. This name was also borne by the American general Benedict Arnold (1741-1801), who defected to Britain during the American Revolution.",
    "Bennett, Ben, Bennie, Benny",
    "BEN-a-dikt",
    341],
    ["Bernard",
    "Derived from the Germanic element bern 'bear' combined with hard 'brave, hardy'. The Normans brought it to England, where it replaced the Old English cognate Beornheard. This was the name of several saints, including Saint Bernard of Menthon who built hospices in the Swiss Alps in the 10th century, and Saint Bernard of Clairvaux, a 12th-century theologian and Doctor of the Church. Other famous bearers include the Irish playwright and essayist George Bernard Shaw (1856-1950) and the British World War II field marshal Bernard Montgomery (1887-1976).",
    "Berard, Berinhard, Bernhard, Barney, Bernie, Berny",
    "ber-NAHRD (English), BUR-nerd (English), ber-NAHR (French), BER-nahrt (Polish, Croatian)",
    489],
    ["Bill",
    "Short form of WILLIAM. This spelling was first used in the 19th century. The change in the initial consonant may have been influenced by an earlier Irish pronunciation of the name. Famous bearers include basketball player Bill Russell (1934-), comedian Bill Cosby (1937-), American president Bill Clinton (1946-), and Microsoft founder Bill Gates (1955-).",
    "Wil, Will, Willie, Willy, Billie, Billy",
    "BIL",
    376],
    ["Blake",
    "From a surname which was derived from Old English blæc 'black' or blac 'pale'. A famous bearer of the surname was the poet and artist William Blake (1757-1827).",
    "",
    "BLAYK",
    96],
    ["Braden",
    "From an Irish surname which was derived from Bradáin meaning 'descendant of BRADÁN'.",
    "Braeden, Braiden, Brayden",
    "BRAY-den",
    414],
    ["Bradley",
    "From an Irish surname which was derived from Bradáin meaning 'descendant of BRADÁN'.",
    "Braeden, Braiden, Brayden",
    "BRAY-den",
    414],
  ]

female_names =
  [["Canada Drives",
    "Suite 600, Two Bentall Centre 555 Burrard Street, Vancouver, BC V7X 1M8",
    "Facilitates auto financing for consumers through an online portal",
    100, 20, "https://www.canadadrives.ca/",
    "https://twitter.com/canadadrives"],
  ]
