
User.new(first_name: "Josh",
         last_name: 'Gamble',
         email: "josh@gmail.com",
         password: "qweqwe",
         password_confirmation: "qweqwe").save(validate: false)
puts "User Josh created!"

User.new(first_name: "Natalie",
         last_name: "Gamble",
         email: "natalie@gmail.com",
         password: "qweqwe",
         password_confirmation: "qweqwe").save(validate: false)
puts "User Natalie created!"

baby_names =
  [["Aaron",
    "From the Hebrew name ('Aharon) which is most likely of unknown Egyptian origin. Other theories claim a Hebrew derivation, and suggest meanings such as 'high mountain' or 'exalted'. In the Old Testament this name is borne by the older brother of Moses. He acted as a spokesman for his brother when they appealed to the pharaoh to release the Israelites from slavery. Aaron's rod produced miracles and plagues to intimidate the pharaoh. After the departure from Egypt and arrival at Mount Sinai, God installed Aaron as the first high priest of the Israelites and promised that his descendants would form the priesthood. As an English name, Aaron has been in use since the Protestant Reformation. This name was borne by the American politician Aaron Burr (1756-1836), notable for killing Alexander Hamilton in a duel.",
    "M",
    "Arron, Aaren (English), Aharon (Hebrew)",
    "AIR-en (English)",
    52],
    ["Adrian",
    "Form of Hadrianus. Several saints and six popes have borne this name, including the only English pope, Adrian IV, and the only Dutch pope, Adrian VI. As an English name, it has been in use since the Middle Ages, though it was not popular until modern times.",
    "M",
    "Hadrianus (Ancient Roman), Adrià (Catalan), Adrijan, Jadran, Jadranko (Croatian), Adriaan, Arjan, Adrianus, Arie",
    "AY-dree-ən (English), AHD-ryahn (Polish), AH-dree-ahn (German), ah-dree-AHN (Russian)",
    58],
    ["Aidan",
    "Anglicized form of AODHÁN. In the latter part of the 20th century it became popular in America due to its sound, since it uses the same fashionable aden suffix sound found in such names as Braden and Hayden.",
    "M",
    "Aodhán, Edan (Irish), Aodhán, Edan (Scottish), Aden, Aiden, Aydan, Ayden (English)",
    "AY-den",
    185],
    ["Alexander",
    "Latinized form of the Greek name (Alexandros), which meant 'defending men' from Greek (alexo) 'to defend, help' and (aner) 'man'. In Greek mythology this was another name of the hero Paris, and it also belongs to several characters in the New Testament. However, the most famous bearer was Alexander the Great, King of Macedon. In the 4th century BC he built a huge empire out of Greece, Egypt, Persia, and parts of India. Due to his fame, and later medieval tales involving him, use of his name spread throughout Europe.",
    "M",
    "Aleksander (Norwegian), Aleksander (Danish), Alexandros (Ancient Greek), Alexandros (Greek Mythology)",
    "a-lig-ZAN-der (English), ah-lek-SAHN-der (German), AW-lek-sawn-der (Hungarian)",
    8],
    ["Andrew",
    "English form of the Greek name (Andreas), which was derived from (andreios) 'manly, masculine', a derivative of (aner) 'man'. In the New Testament the apostle Andrew, the first disciple to join Jesus, is the brother of Simon Peter. According to tradition, he later preached in the Black Sea region, with some legends saying he was crucified on an X-shaped cross. Andrew, being a Greek name, was probably only a nickname or a translation of his real Hebrew name, which is not known. This name has been common (in various spellings) throughout the Christian world, and it became very popular in the Middle Ages. Saint Andrew is regarded as the patron of Scotland, Russia, Greece and Romania. The name has been borne by three kings of Hungary, American president Andrew Jackson (1767-1845), and, more recently, English composer Andrew Lloyd Webber (1948-).",
    "M",
    "Andre, Andreas, Andie, Andy, Drew",
    "AN-droo (English)",
    30],
    ["Anthony",
    "English form of the Roman family name Antonius, which is of unknown Etruscan origin. The most notable member of the Roman family was the general Marcus Antonius (called Mark Antony in English), who for a period in the 1st century BC ruled the Roman Empire jointly with Augustus. When their relationship turned sour, he and his mistress Cleopatra were attacked and forced to commit suicide, as related in Shakespeare's tragedy 'Antony and Cleopatra' (1606). The name became regularly used in the Christian world due to the fame of Saint Anthony the Great, a 4th-century Egyptian hermit who founded Christian monasticism. Its popularity was reinforced in the Middle Ages by the 13th-century Saint Anthony of Padua, the patron saint of Portugal. It has been commonly (but incorrectly) associated with Greek ανθος (anthos) 'flower', which resulted in the addition of the h to this spelling in the 17th century.",
    "M",
    "Antony, Tony, Antonia",
    "AN-tha-nee, AN-ta-nee",
    25],
    ["Arnold",
    "From a Germanic name meaning 'eagle power', derived from the elements arn 'eagle' and wald 'power'. The Normans brought it to England, where it replaced the Old English cognate Earnweald. It died out as an English name after the Middle Ages, but it was revived in the 19th century.Saints bearing the name include an 8th-century musician in the court of Charlemagne and an 11th-century French bishop who is the patron saint of brewers. It was also borne by Arnold of Brescia, a 12th-century Augustinian monk who rebelled against the church and was eventually hanged. Famous modern bearers include American golfer Arnold Palmer (1929-) and Austrian-American actor and politician Arnold Schwarzenegger (1947-).",
    "M",
    "Arn, Arnie (English), Arndt, Arne, Arno (German), Arnau (Catalan), Arnoud, Arnout, Aart, Arend, Arno (Dutch), Arnaud (French), Ane, Anne, Arke (Frisian), Arnaldo (Italian), Nöl, Nölke (Limburgish), Arnt (Norwegian)",
    "AHR-neld (English), AHR-nawlt (German)",
    357],
    ["Austin",
    "Medieval contracted form of AUGUSTINE (1). Modern use of the name is probably also partly inspired by the common surname Austin, which is of the same origin. This is also the name of a city in Texas.",
    "M",
    "Augustine, Austen, Austyn",
    "AWS-tin",
    69],
    ["Baldwin",
    "Derived from the Germanic elements bald 'bold, brave' and win 'friend'. In the Middle Ages this was a popular name in Flanders and among the Normans, who brought it to Britain. It was borne by one of the leaders of the First Crusade, an 11th-century nobleman from Flanders. After the crusaders conquered Jerusalem, he was crowned as the king of the Kingdom of Jerusalem.",
    "M",
    "Boudewijn, Boele (Dutch), Baudouin (French), Baldovino, Baldo (Italian), Balduíno (Portuguese), Balduino, Baldo (Spanish), Maldwyn (Welsh)",
    "BAWLD-win (English)",
    680],
    ["Benedict",
    "From the Late Latin name Benedictus which meant 'blessed'. Saint Benedict was an Italian monk who founded the Benedictines in the 6th century. After his time the name was common among Christians, being used by 16 popes. In England it did not come into use until the 12th century, at which point it became very popular. This name was also borne by the American general Benedict Arnold (1741-1801), who defected to Britain during the American Revolution.",
    "M",
    "Bennett, Ben, Bennie, Benny",
    "BEN-a-dikt",
    341],
    ["Bernard",
    "Derived from the Germanic element bern 'bear' combined with hard 'brave, hardy'. The Normans brought it to England, where it replaced the Old English cognate Beornheard. This was the name of several saints, including Saint Bernard of Menthon who built hospices in the Swiss Alps in the 10th century, and Saint Bernard of Clairvaux, a 12th-century theologian and Doctor of the Church. Other famous bearers include the Irish playwright and essayist George Bernard Shaw (1856-1950) and the British World War II field marshal Bernard Montgomery (1887-1976).",
    "M",
    "Berard, Berinhard, Bernhard, Barney, Bernie, Berny",
    "ber-NAHRD (English), BUR-nerd (English), ber-NAHR (French), BER-nahrt (Polish, Croatian)",
    489],
    ["Bill",
    "Short form of WILLIAM. This spelling was first used in the 19th century. The change in the initial consonant may have been influenced by an earlier Irish pronunciation of the name. Famous bearers include basketball player Bill Russell (1934-), comedian Bill Cosby (1937-), American president Bill Clinton (1946-), and Microsoft founder Bill Gates.",
    "M",
    "Wil, Will, Willie, Willy, Billie, Billy",
    "BIL",
    376],
    ["Braden",
    "From an Irish surname which was derived from Bradáin meaning 'descendant of BRADÁN'.",
    "M",
    "Braeden, Braiden, Brayden",
    "BRAY-den",
    414],
    ["Bradley",
    "From a surname which originally came from a place name meaning 'broad clearing' in Old English. A famous bearer of the surname was the World War II American general Omar Bradley (1893-1981).",
    "M",
    "Brad",
    "BRAD-lee",
    473],
    ["Brendan",
    "From Brendanus, the Latinized form of the Irish name Bréanainn which was derived from a Welsh word meaning 'prince'. Saint Brendan was a 6th-century Irish abbot who, according to legend, crossed the Atlantic and reached North America with 17 other monks.",
    "M",
    "Breandán, Brendanus (Irish), Brenden, Brendon (English)",
    "BREN-den",
    388],
    ["Brian",
    "The meaning of this name is not known for certain but it is possibly related to the old Celtic element bre meaning 'hill', or by extension 'high, noble'. It was borne by the semi-legendary Irish king Brian Boru, who thwarted Viking attempts to conquer Ireland in the 11th century. He was slain in the Battle of Clontarf, though his forces were decisively victorious. The name was common in Ireland before his time, and even more so afterwards. It came into use in England in the Middle Ages, introduced by Breton settlers. It subsequently became rare, but was revived in the 20th century.",
    "M",
    "Brion, Bryan, Bryon",
    "BRIE-en",
    188],
    ["Buddy",
    "From the English word meaning 'friend'. It probably originated as a nursery form of the word brother.",
    "M",
    "Bud",
    "BUD-ee",
    748],
    ["Caden",
    "Sometimes explained as a derivative of the Irish surname Caden, which is a reduced form of the Gaelic surname Mac Cadáin meaning 'son of Cadán'. In actuality, its popularity in America beginning in the 1990s is due to its sound - it shares its fashionable aden suffix sound with other popular names like Hayden, Aidan and Braden.",
    "M",
    "Caiden, Cayden, Kaden, Kaeden, Kaiden, Kayden",
    "KAY-den",
    192],
    ["Caleb",
    "Most likely related to Hebrew (kelev) meaning 'dog'. An alternate theory connects it to Hebrew (kal) 'whole, all of' and (lev) 'heart'. In the Old Testament this is the name of one of the twelve spies sent by Moses into Canaan. Of the Israelites who left Egypt with Moses, Caleb and Joshua were the only ones who lived to see the Promised Land. As an English name, Caleb came into use after the Protestant Reformation. It was common among the Puritans, who introduced it to America in the 17th century.",
    "M",
    "Kaleb, Cale, Chaleb, Kalev, Chaleb",
    "KAY-leb",
    37],
    ["Calvin",
    "Derived from the French surname Chauvin, which was derived from chauve 'bald'. The surname was borne by Jean Chauvin (1509-1564), a theologian from France who was one of the leaders of the Protestant Reformation. His surname was Latinized as Calvinus (based on Latin calvus 'bald') and he is known as John Calvin in English. It has been used as a given name in his honour since the 19th century.",
    "M",
    "Cal",
    "KAL-vin",
    171],
    ["Chad",
    "From the Old English name Ceadda which is of unknown meaning, possibly based on Welsh cad 'battle'. This was the name of a 7th-century English saint. Borne primarily by Catholics, it was a rare name until the 1960s when it started to become more common amongst the general population. This is also the name of a country in Africa, though it originates from a different source.",
    "M",
    "Shad, Ceadda",
    "CHAD",
    763],
    ["Chester",
    "From a surname which originally belonged to a person who came from Chester, an old Roman settlement in Britain. The name of the settlement came from Latin castrum 'camp, fortress'.",
    "M",
    "Chet",
    "CHES-ter",
    531],
    ["Christopher",
    "From the Late Greek name (Christophoros) meaning 'bearing CHRIST', derived from (Christos) combined with (phero) 'to bear, to carry'. Early Christians used it as a metaphorical name, expressing that they carried Christ in their hearts. In the Middle Ages, literal interpretations of the name's etymology led to legends about a Saint Christopher who carried the young Jesus across a river. He has come to be regarded as the patron saint of travellers.",
    "M",
    "Kristopher, Chip, Chris, Kit, Kris, Topher",
    "KRIS-ta-fer",
    32],
    ["Cody",
    "From the Gaelic surname Cuidighthigh, which means 'descendant of CUIDIGHTHEACH'. A famous bearer of the surname was the American frontiersman and showman Buffalo Bill Cody (1846-1917).",
    "M",
    "Codie, Coty, Kody, Kodey",
    "KO-dee",
    237],
    ["Conor",
    "Anglicized form of the Gaelic name Conchobhar which means 'dog lover' or 'wolf lover'. It has been in use in Ireland for centuries and was the name of several Irish kings. It was also borne by the legendary Ulster king Conchobar mac Nessa, known for his tragic desire for Deirdre.",
    "M",
    "Conchobhar, Connor, Conchúr",
    "KAHN-er",
    477],
    ["Courtney",
    "From an aristocratic English surname which was derived either from the French place name Courtenay (originally a derivative of the personal name Curtenus, itself derived from Latin curtus 'short') or else from a Norman nickname meaning 'short nose'. As a feminine name in America, it first became popular during the 1970s.",
    "M",
    "Cortney, Kortney, Kourtney",
    "KORT-nee",
    752],
    ["Cyrus",
    "From Κυρος (Kyros), the Greek form of the Persian name Kūrush, which may mean 'far sighted' or 'young'. The name is sometimes associated with Greek (kyrios) 'lord'. It was borne by several kings of Persia, including Cyrus the Great, who conquered Babylon. He is famous in the Old Testament for freeing the captive Jews and allowing them to return to Israel. As an English name, it first came into use among the Puritans after the Protestant Reformation.",
    "M",
    "Kyros, Cy, Kyra, Kyros, Ciro",
    "SIE-rus",
    472],
    ["Damon",
    "Derived from Greek (damazo) meaning 'to tame'. According to Greek legend, Damon and Pythias were friends who lived on Syracuse in the 4th century BC. When Pythias was sentenced to death, he was allowed to temporarily go free on the condition that Damon take his place in prison. Pythias returned just before Damon was to be executed in his place, and the king was so impressed with their loyalty to one another that he pardoned Pythias. As an English given name, it has only been regularly used since the 20th century.",
    "M",
    "Damianos, Damianus (Ancient Greek), Damyan (Bulgarian), Damjan (Croatian), Damiaan, Damian (Dutch), Damien (French), Damiano (Italian), Damjan (Macedonian), Damian (Polish), Demyan (Russian), Damjan (Serbian), Damijan, Damjan (Slovene), Demyan (Ukrainian)",
    "DAY-mun",
    427],
    ["Daniel",
    "From the Hebrew name (Daniyyel) meaning 'God is my judge'. Daniel was a Hebrew prophet whose story is told in the Book of Daniel in the Old Testament. He lived during the Jewish captivity in Babylon, where he served in the court of the king, rising to prominence by interpreting the king's dreams. The book also presents Daniel's four visions of the end of the world. Due to the popularity of the biblical character, the name came into use in England during the Middle Ages. Though it became rare by the 15th century, it was revived after the Protestant Reformation. Famous bearers of this name include English author Daniel Defoe (1660-1731), Swiss mathematician Daniel Bernoulli (1700-1782), and American frontiersman Daniel Boone (1734-1820).",
    "M",
    "Danilo (Spanish), Danilo (Portuguese), Danijel, Danilo (Slovene), Danail (Bulgarian), Danijel, Danilo (Croatian), Taniel (Armenian)",
    "DAN-yəl (English), dah-nee-EL (Jewish), dan-YEL (French), DAH-nee-el (German), DAHN-yel (Polish)",
    12],
    ["Darren",
    "The meaning of this name is not known for certain. It could be from a rare Irish surname or it could be an altered form of DARRELL. It was first brought to public attention in the late 1950s by the American actor Darren McGavin (1922-2006). It was further popularized in the 1960s by the character Darrin Stephens from the television show 'Bewitched'.",
    "M",
    "Daren, Darian, Darien, Darin, Darion, Darrin, Derren",
    "DER-en, DAR-en",
    540],
    ["David",
    "From the Hebrew name (Dawid), which was probably derived from Hebrew (dwd) meaning 'beloved'. David was the second and greatest of the kings of Israel, ruling in the 10th century BC. Several stories about him are told in the Old Testament, including his defeat of Goliath, a giant Philistine. According to the New Testament, Jesus was descended from him. This name has been used in Britain since the Middle Ages. It has been especially popular in Wales, where it is used in honour of the 5th-century patron saint of Wales (also called Dewi), as well as in Scotland, where it was borne by two kings. Famous bearers include empiricist philosopher David Hume (1711-1776), explorer David Livingstone (1813-1873), musician David Bowie (1947-2016), and soccer player David Beckham (1975-). This is also the name of the hero of Charles Dickens' semi-autobiographical novel 'David Copperfield' (1850).",
    "M",
    "Dovid, Dàibhidh, Daividh, Davi, Dave, Davey, Davie, Davy, Davie",
    "DAY-vid (English), dah-VEED (Jewish, Spanish), da-VEED (French), DAH-vit (German, Dutch), DAH-vid (Swedish, Norwegian), dah-VEET (Russian)",
    18],
    ["Denis",
    "From Denys or Denis, the medieval French forms of DIONYSIUS. Saint Denis was a 3rd-century missionary to Gaul and the first bishop of Paris. He was martyred by decapitation, after which legend says he picked up his own severed head and walked for a distance while preaching a sermon. He is credited with converting the Gauls to Christianity and is considered the patron saint of France. This name was common in France during the Middle Ages, and it was imported by the Normans to England. It is now regularly spelled Dennis in the English-speaking world. A notable bearer was the French philosopher Denis Diderot (1713-1784).",
    "M",
    "Dennis (English), Dennis (German), Dionýz (Slovak), Dionisie (Romanian), Den, Denny",
    "de-NEE (French), DEN-is (English), DE-nis (German)",
    351],
    ["Dirk",
    "Short form of DIEDERIK. The name was popularized in the English-speaking world by actor Dirk Bogarde (1921-1999), who had some Dutch ancestry. This is also the Scots word for a type of dagger.",
    "M",
    "Dick, Diede, Ties (Dutch), Dierk (German)",
    "DIRK (Dutch), DEERK (German), DURK (English)",
    210],
    ["Douglas",
    "Anglicized form of the Scottish surname Dubhghlas, meaning 'dark river' from Gaelic dubh 'dark' and glais 'water, river'. Douglas was originally a river name, which then became a Scottish clan name (belonging to a powerful line of Scottish earls). It has been used as a given name since the 16th century.",
    "M",
    "Dubhghlas (Scottish), Doug",
    "DUG-les",
    617],
    ["Duncan",
    "Anglicized form of the Gaelic name Donnchadh meaning 'brown warrior', derived from Gaelic donn 'brown' and cath 'warrior'. This was the name of two kings of Scotland, including the one who was featured in Shakespeare's play 'Macbeth' (1606).",
    "M",
    "Donnchad, Donnchadh, Donagh, Donnchad, Donnchadh",
    "DUN-ken",
    802],
    ["Edgar",
    "Derived from the Old English elements ead 'wealth, fortune' and gar 'spear'. This was the name of a 10th-century English king, Edgar the Peaceful. The name did not survive long after the Norman conquest, but it was revived in the 18th century, in part due to a character by this name in Sir Walter Scott's novel 'The Bride of Lammermoor' (1819), which tells of the tragic love between Edgar Ravenswood and Lucy Ashton. Famous bearers include author and poet Edgar Allan Poe (1809-1849), French impressionist painter Edgar Degas (1834-1917), and author Edgar Rice Burroughs (1875-1950).",
    "M",
    "Eadgar (Anglo-Saxon), Edgardo (Italian), Edgaras (Lithuanian), Edgardo (Spanish), Ed, Eddie, Eddy, Edgard",
    "ED-ger (English), ed-GAHR (French)",
    342],
    ["Elijah",
    "From the Hebrew name ('Eliyyahu) meaning 'my God is YAHWEH'. Elijah was a Hebrew prophet and miracle worker, as told in the two Books of Kings in the Old Testament. He was active in the 9th century BC during the reign of King Ahab of Israel and his Phoenician-born queen Jezebel. Elijah confronted the king and queen over their idolatry of the Canaanite god Ba'al and other wicked deeds. At the end of his life he was carried to heaven in a chariot of fire, and was succeeded by Elisha. In the New Testament, Elijah and Moses appear next to Jesus when he is transfigured. Because Elijah was a popular figure in medieval tales, and because his name was borne by a few early saints (who are usually known by the Latin form Elias), the name came into general use during the Middle Ages. In medieval England it was usually spelled Elis. It died out there by the 16th century, but it was revived by the Puritans in the form Elijah after the Protestant Reformation.",
    "M",
    "Eliyahu, Eliyyahu, Elias, Ilya, Ilija",
    "i-LIE-jə (English), i-LIE-zhə (English)",
    9],
    ["Emmanuel",
    "From the Hebrew name ('Immanu'el) meaning 'God is with us'. This was the foretold name of the Messiah in the Old Testament. It has been used in England since the 16th century in the spellings Emmanuel and Immanuel, though it has not been widespread. The name has been more common in continental Europe, especially in Spain and Portugal (in the spellings Manuel and Manoel).",
    "M",
    "Manuel, Manu, Manny, Imanol, Manoel",
    "e-man-WEL (French), i-MAN-ye-wel, i-MAN-wel (English)",
    157],
    ["Eric",
    "From the Old Norse name Eiríkr, derived from the elements ei 'ever, always' and ríkr 'ruler'. A notable bearer was Eiríkr inn Rauda (Eric the Red in English), a 10th-century navigator and explorer who discovered Greenland. This was also the name of several early kings of Sweden, Denmark and Norway. This common Norse name was first brought to England by Danish settlers during the Anglo-Saxon period. It was not popular in England in the Middle Ages, but it was revived in the 19th century, in part due to the children's novel 'Eric, or Little by Little' (1858) by Frederic William Farrar.",
    "M",
    "Aric, Erik, Erich, Eero, Eryk",
    "ER-ik",
    142],
    ["Ethan",
    "From the Hebrew name ('Eitan) meaning 'solid, enduring, firm'. In the Old Testament this name is borne by a few minor characters, including the wise man Ethan the Ezrahite, supposedly the author of Psalm 89. After the Protestant Reformation it was occasionally used as a given name in the English-speaking world, and it became somewhat common in America due to the fame of the revolutionary Ethan Allen (1738-1789). It only became popular towards the end of the 20th century. It is the name of the main character in Edith Wharton's novel 'Ethan Frome' (1911), about a man in love with his wife's cousin.",
    "M",
    "Eitan, Eytan, Aithan",
    "EE-than",
    10],
    ["Ezra",
    "Means 'help' in Hebrew. Ezra is a prophet of the Old Testament and the author of the Book of Ezra. It has been used as a given name in the English-speaking world since the Protestant Reformation. The American poet Ezra Pound (1885-1972) was a famous bearer.",
    "M",
    "Esdras, Ezras",
    "EZ-ra",
    85],
    ["Felix",
    "From a Roman cognomen meaning 'lucky, successful' in Latin. It was acquired as an agnomen, or nickname, by the 1st-century BC Roman general Sulla. It also appears in the New Testament belonging to the governor of Judea who imprisoned Saint Paul. Due to its favourable meaning, this name was popular among early Christians, being borne by many early saints and four popes. It has been used in England since the Middle Ages, though it has been more popular in continental Europe. A notable bearer was the German composer Felix Mendelssohn (1809-1847).",
    "M",
    "Phelix, Feliu, Feliks,",
    "FE-liks (German, Swedish), FAY-liks (Dutch), FEE-liks (English)",
    247],
    ["Francis",
    "English form of the Late Latin name Franciscus which meant 'Frenchman', ultimately from the Germanic tribe of the Franks, who were named for a type of spear that they used. This name was borne by the 13th-century Saint Francis of Assisi, who was originally named Giovanni but was given the nickname Francesco by his father, an admirer of the French. Francis went on to renounce his father's wealth and devote his life to the poor, founding the Franciscan order of friars. Later in his life he apparently received the stigmata. Due to the renown of the saint, this name became widespread in Western Europe during the Middle Ages. However, it was not regularly used in Britain until the 16th century. Famous bearers include Saint Francis Xavier (1506-1552), a missionary to East Asia, the philosopher and scientist Francis Bacon (1561-1626), and the explorer and admiral Sir Francis Drake (1540-1595). In the English-speaking world this name is occasionally used for girls.",
    "M",
    "Francois, Franko, Frank, Franky, Francisco, Frans",
    "FRAN-sis",
    478],
    ["Frederick",
    "English form of a Germanic name meaning peaceful ruler', derived from frid 'peace' and ric 'ruler, power'. This name has long been common in continental Germanic-speaking regions, being borne by rulers of the Holy Roman Empire, Germany, Austria, Scandinavia, and Prussia. Notables among these rulers include the 12th-century Holy Roman Emperor and crusader Frederick I Barbarossa, the 13th-century emperor and patron of the arts Frederick II, and the 18th-century Frederick II of Prussia, known as Frederick the Great. The Normans brought the name to England in the 11th century but it quickly died out. It was reintroduced by the German House of Hanover when they inherited the British throne in the 18th century. A famous bearer was Frederick Douglass (1818-1895), an American ex-slave who became a leading advocate of abolition.",
    "M",
    "Fred, Freddie, Freddy, Frederico, Frits, Fryderyk",
    "FRED-e-rik, FRED-rik",
    513],
    ["Gabriel",
    "From the Hebrew name (Gavri'el) meaning 'God is my strong man'. Gabriel was one of the seven archangels in Hebrew tradition, often appearing as a messenger of God. In the Old Testament he is sent to interpret the visions of the prophet Daniel, while in the New Testament he serves as the announcer of the births of John to Zechariah and Jesus to Mary. According to Islamic tradition he was the angel who dictated the Qur'an to Muhammad. This name has been used occasionally in England since the 12th century. It was not common in the English-speaking world until the end of the 20th century.",
    "M",
    "Gavril, Kaapro, Jabril, Gabrijel, Gavriil, Dzhabrail",
    "ga-bree-EL (French), GAH-bryel (Spanish), GAHP-ree-el (German), GAHB-ree-el (Finnish), GAY-bree-el (English), GAHP-ryel (Polish)",
    25],
    ["Geoffrey",
    "From a Norman French form of a Germanic name. The second element is Germanic frid 'peace', but the first element may be either gawia 'territory', walha 'foreign' or gisil 'hostage'. It is possible that two or more names merged into a single form. In the later Middle Ages Geoffrey was further confused with the distinct name Godfrey. The Normans introduced this name to England where it became common among the nobility. Famous medieval literary bearers include the 12th-century chronicler Geoffrey of Monmouth and the 14th-century poet Geoffrey Chaucer, writer of 'The Canterbury Tales'. By the end of the Middle Ages it had become uncommon, but it was revived in the 20th century, often in the spelling Jeffrey.",
    "M",
    "Godfrey, Jeffrey, Jeff, Godfried, Fredo, Joffrey, Geoff",
    "JEF-ree (English), zhaw-FRE (French)",
    318],
    ["George",
    "From the Greek name (Georgios) which was derived from the Greek word (georgos) meaning 'farmer, earthworker', itself derived from the elements (ge) 'earth' and (ergon) 'work'. Saint George was a 3rd-century Roman soldier from Palestine who was martyred during the persecutions of emperor Diocletian. Later legends describe his defeat of a dragon, with which he was often depicted in medieval art. Initially Saint George was primarily revered by Eastern Christians, but returning crusaders brought stories of him to Western Europe and he became the patron of England, Portugal, Catalonia and Aragon. The name was rarely used in England until the German-born George I came to the British throne in the 18th century. Five subsequent British kings have borne the name. Other famous bearers include two kings of Greece, the composer George Frideric Handel (1685-1759), the first president of the United States, George Washington (1732-1797), and the Pacific explorer George Vancouver (1757-1798). This was also the pen name of authors George Eliot (1819-1880) and George Orwell (1903-1950), real names Mary Anne Evans and Eric Arthur Blair respectively.",
    "M",
    "Geordie, Georgie, Jorge, Yuri, Goran, Giorgio, Jordi, Jurgis",
    "JORJ (English)",
    125],
    ["Gordon",
    "From a Scottish surname which was originally derived from a place name meaning 'spacious fort'. It was originally used in honour of Charles George Gordon (1833-1885), a British general who died defending the city of Khartoum in Sudan.",
    "M",
    "Gorden, Gord, Gordie, Gordy",
    "GAWR-den",
    948],
    ["Graham",
    "From a Scottish surname, originally derived from the English place name Grantham, which probably meant 'gravelly homestead' in Old English. The surname was first taken to Scotland in the 12th century by the Norman baron William de Graham. A famous bearer was Alexander Graham Bell (1847-1922), the Scottish-Canadian-American inventor who devised the telephone.",
    "M",
    "Graeme, Grahame",
    "GRAY-em, GRAM",
    179],
    ["Guy",
    "Norman French form of WIDO. The Normans introduced it to England, where it was common until the time of Guy Fawkes (1570-1606), a revolutionary who attempted to blow up the British parliament. The name was revived in the 19th century, due in part to characters in the novels 'Guy Mannering' (1815) by Sir Walter Scott and 'The Heir of Redclyffe' (1854) by C. M. Yonge.",
    "M",
    "Wido, Vid, Guido, Gvidas, Wit",
    "GIE (English), GEE (French)",
    1124],
    ["Harold",
    "From the Old English name Hereweald, derived from the elements here 'army' and weald 'power, leader, ruler'. The Old Norse cognate Haraldr was also common among Scandinavian settlers in England. This was the name of five kings of Norway and three kings of Denmark. It was also borne by two kings of England, both of whom were from mixed Scandinavian and Anglo-Saxon backgrounds, including Harold II who lost the Battle of Hastings (and was killed in it), which led to the Norman conquest. After the conquest the name died out, but it was eventually revived in the 19th century.",
    "M",
    "Hal, Harry, Harri, Haroldo, Harald",
    "HER-eld, HAR-eld",
    802],
    ["Hayden",
    "From an English surname which was derived from place names meaning either 'hay valley' or 'hay hill', derived from Old English heg 'hay' and denu 'valley' or dun 'hill'.",
    "M",
    "Hal, Harry, Harri, Haroldo, Harald",
    "HAY-den",
    169],
    ["Hector",
    "Latinized form of Greek (Hektor), which was derived from (hektor) 'holding fast', ultimately from (echo) meaning 'to hold, to possess'. In Greek legend Hector was one of the Trojan champions who fought against the Greeks. After he killed Achilles' friend Patroclus in battle, he was himself brutally slain by Achilles, who proceeded to tie his dead body to a chariot and drag it about. This name also appears in Arthurian legends belonging to King Arthur's foster father. Hector has occasionally been used as a given name since the Middle Ages, probably because of the noble character of the classical hero. It was historically common in Scotland, where it was used as an Anglicized form of Eachann.",
    "M",
    "Hektor, Ettore, Heitor",
    "HEK-ter",
    319],
    ["Howard",
    "From an English surname which can derive from several different sources: the Anglo-Norman given name Huard, which was from the Germanic name HUGHARD; the Anglo-Scandinavian given name Haward, from the Old Norse name HÁVARÐR; or the Middle English term ewehirde meaning 'ewe herder'. This is the surname of a British noble family, members of which have held the title Duke of Norfolk from the 15th century to the present. A famous bearer of the given name was the American industrialist Howard Hughes (1905-1976).",
    "M",
    "Howie",
    "HOW-erd",
    899],
    ["Hugh",
    "From the Germanic element hug, meaning 'heart, mind, spirit'. It was common among Frankish and French nobility, being borne by Hugh Capet, a 10th-century king of France who founded the Capetian dynasty. The Normans brought the name to England and it became common there, even more so after the time of the 12th-century bishop Saint Hugh of Lincoln, who was known for his charity. This was also the name of kings of Cyprus and the crusader kingdom of Jerusalem. The name is used in Ireland and Scotland as the Anglicized form of Aodh and Ùisdean.",
    "M",
    "Hugo, Huey, Hughie, Hewie, Ugo, Huw",
    "HYOO",
    850],
    ["Inigo",
    "English form of ÍÑIGO. It became well-known in Britain due to the 17th-century English architect Inigo Jones. He was named after his father, a Catholic who was named for Saint Ignatius of Loyola.",
    "M",
    "Eneko, Inigo",
    "In-i-go",
    1893],
    ["Irving",
    "From a Scottish surname which was in turn derived from a Scottish place name meaning 'green water'. Historically this name has been relatively common among Jews, who have used it as an American-sounding form of Hebrew names beginning with I such as Isaac, Israel and Isaiah. A famous bearer was the Russian-American songwriter and lyricist Irving Berlin (1888-1989), whose birth name was Israel Beilin.",
    "M",
    "Irvin, Irvine",
    "UR-ving",
    1350],
    ["Isaiah",
    "From the Hebrew name (Yesha'yahu) meaning 'YAHWEH is salvation'. Isaiah is one of the four major prophets of the Old Testament, supposedly the author of the Book of Isaiah. He was from Jerusalem and probably lived in the 8th century BC, at a time when Assyria threatened the Kingdom of Judah. As an English Christian name, Isaiah was first used after the Protestant Reformation.",
    "M",
    "Isiah, Isaias, Esaias, Esa, Isaia, Isay",
    "ie-ZAY-a (English), ie-ZIE-a",
    47],
    ["Ivan",
    "Newer form of the old Slavic name (Ioannu), which was derived from Greek Ioannes (see JOHN). This was the name of six Russian rulers, including the 15th-century Ivan III the Great and 16th-century Ivan IV the Terrible, the first tsar of Russia. It was also borne by nine emperors of Bulgaria. Other notable bearers include the Russian author Ivan Turgenev (1818-1883), who wrote 'Fathers and Sons', and the Russian physiologist Ivan Pavlov (1849-1936), who is best known for his discovery of the conditioned reflex.",
    "M",
    "Ioann, Yoan, Yan, Jovan, Ivano, Vanya, Ivo",
    "ee-VAHN (Russian, Ukrainian), IE-ven (English)",
    131],
    ["Jack",
    "Derived from Jackin (earlier Jankin), a medieval diminutive of JOHN. It is often regarded as an independent name. During the Middle Ages it was very common, and it became a slang word meaning 'man'. It was frequently used in fairy tales and nursery rhymes, such as 'Jack and the Beanstalk', 'Little Jack Horner', and 'Jack Sprat'. American writers Jack London (1876-1916) and Jack Kerouac (1922-1969) were two famous bearers of this name. It is also borne by American actor Jack Nicholson.",
    "M",
    "Jake, Jackie, Jackson",
    "JAK",
    38],
    ["Jacob",
    "From the Latin Iacobus, which was from the Greek (Iakobos), which was from the Hebrew name (Ya'aqov). In the Old Testament Jacob (later called Israel) is the son of Isaac and Rebecca and the father of the twelve founders of the twelve tribes of Israel. He was born holding his twin brother Esau's heel, and his name is explained as meaning 'holder of the heel' or 'supplanter', because he twice deprived his brother of his rights as the firstborn son (see Genesis 27:36). Other theories claim that it is in fact derived from a hypothetical name like (Ya'aqov'el) meaning 'may God protect'. The English names Jacob and James derive from the same source, with James coming from Latin Iacomus, a later variant of Iacobus. Unlike English, many languages do not have separate spellings for the two names.In England, Jacob was mainly regarded as a Jewish name during the Middle Ages, though the variant James was used among Christians. Jacob came into general use as a Christian name after the Protestant Reformation. A famous bearer was Jacob Grimm (1785-1863), the German linguist and writer who was, with his brother Wilhelm, the author of 'Grimm's Fairy Tales'.",
    "M",
    "Jaycob, Jacobus, Jakob, Akiba, Akiva, Yaakov, Coby, Jeb",
    "JAY-kub (English), YAH-kawp (Dutch)",
    7],
    ["Jason",
    "From the Greek name (Iason), which was derived from Greek (iasthai) 'to heal'. In Greek mythology Jason was the leader of the Argonauts. After his uncle Pelias overthrew his father Aeson as king of Iolcos, Jason went in search of the Golden Fleece in order to win back the throne. During his journeys he married the sorceress Medea, who helped him gain the fleece and kill his uncle, but who later turned against him when he fell in love with another woman. This name also appears in the New Testament, belonging to man who sheltered Paul and Silas. In his case, it may represent a Hellenized form of a Hebrew name. It was not used in England until after the Protestant Reformation.",
    "M",
    "Jayson, Jace, Jay, Jae, JSON",
    "JAY-son",
    84],
    ["Jeremy",
    "Medieval English form of JEREMIAH, and the form used in some English versions of the New Testament.",
    "M",
    "Jez, Jem, Jemmy, Jerry, Jeremiah, Jere",
    "JER-a-mee (English), JER-mee",
    184],
    ["John",
    "English form of Iohannes, the Latin form of the Greek name (Ioannes), itself derived from the Hebrew name (Yochanan) meaning 'YAHWEH is gracious'. The Hebrew form occurs in the Old Testament (spelled Johanan or Jehohanan in the English version), but this name owes its popularity to two New Testament characters, both highly revered saints. The first is John the Baptist, a Jewish ascetic who is considered the forerunner of Jesus. He baptized Jesus and was later executed by Herod Antipas. The second is the apostle John, who is traditionally regarded as the author of the fourth gospel and Revelation. With the apostles Peter and James (his brother), he was part of the inner circle of Jesus.",
    "M",
    "Ian, Jon, Johnnie, Johnny",
    "JAHN",
    28],
    ["Joshua",
    "From the Hebrew name (Yehoshu'a) meaning 'YAHWEH is salvation'. As told in the Old Testament, Joshua was a companion of Moses. He went up Mount Sinai with Moses when he received the Ten Commandments from God, and later he was one of the twelve spies sent into Canaan. After Moses died Joshua succeeded him as leader of the Israelites and he led the conquest of Canaan. His original name was Hoshea. The name Jesus comes from a Greek translation of the Aramaic short form (Yeshu'a), which was the real name of Jesus. As an English name, Joshua has been in use since the Protestant Reformation.",
    "M",
    "Josh, Yeshua, Essa, Isa, Josu, Jozua, Josue, Giosue, Yushua",
    "JAH-sha-wa (English), JAW-shwa",
    35],
    ["Julius",
    "From a Roman family name which was possibly derived from Greek (ioulos) 'downy-bearded'. Alternatively, it could be related to the name of the Roman god JUPITER. This was a prominent patrician family of Rome, who claimed descent from the mythological Julus, son of Aeneas. Its most notable member was Gaius Julius Caesar, who gained renown as a military leader for his clever conquest of Gaul. After a civil war he became the dictator of the Roman Republic, but was eventually stabbed to death in the senate. Although this name was borne by several early saints, including a pope, it was rare during the Middle Ages. It was revived in Italy and France during the Renaissance, and was subsequently imported to England.",
    "M",
    "Iulius, Jules, Giulio, Juliusz, Julio, Yuli, Julij",
    "YOO-li-uws (Ancient Roman), JOO-lee-es (English), YOO-lee-uws (German)",
    340],
    ["Justin",
    "From the Latin name Iustinus, which was derived from JUSTUS. This was the name of several early saints including Justin Martyr, a Christian philosopher of the 2nd century who was beheaded in Rome. It was also borne by two Byzantine emperors. As an English name, it has occasionally been used since the late Middle Ages, though it did not become common until the 20th century. Famous modern bearers include pop stars Justin Timberlake and Justin Bieber.",
    "M",
    "Justy, Giustino, Justyn",
    "JUS-tin",
    113],
    ["Keegan",
    "From an Irish surname, the Anglicized form of the Gaelic Mac Aodhagáin, which means 'descendant of Aodhagán'. The given name Aodhagán is a double diminutive of AODH.",
    "M",
    "Kegan",
    "KEE-gen",
    282],
    ["Keith",
    "From a Scottish surname which was originally derived from a place name, itself probably derived from the Brythonic element cet meaning 'wood'. This was the surname of a long line of Scottish nobles. It has been used as a given name since the 19th century.",
    "M",
    "Keitha",
    "KEETH",
    484],
    ["Kelly",
    "Anglicized form of the Irish given name CEALLACH or the surname derived from Ceallaigh. As a surname, it has been borne by actor and dancer Gene Kelly (1912-1996) and actress and princess Grace Kelly (1929-1982).",
    "M",
    "Ceallagh, Kelley, Kelli, Kelleigh, Kellan",
    "KEL-ee",
    514],
    ["Kendrick",
    "From a surname which has several different origins. It could be from the Old English given names Cyneric 'royal power' or Cenric 'bold power', or from the Welsh name Cynwrig 'chief hero'. It can also be an Anglicized form of the Gaelic surname Mac Eanraig meaning 'son of HENRY'.",
    "M",
    "Kenrick",
    "KEN-drik",
    386],
    ["Kevin",
    "Anglicized form of the Irish name Caoimhín, derived from the older Irish Cóemgein, composed of the Old Irish elements cóem 'kind, gentle, handsome' and gein 'birth'. Saint Caoimhín established a monastery in Glendalough, Ireland in the 6th century and is the patron saint of Dublin. It became popular in the English-speaking world outside of Ireland in the 20th century.",
    "M",
    "Kevyn, Kevan, Kev, Cefin",
    "KEV-in",
    89],
    ["Laurence",
    "From the Roman cognomen Laurentius, which meant 'from Laurentum'. Laurentum was a city in ancient Italy, its name probably deriving from Latin laurus 'laurel'. Saint Laurence was a 3rd-century deacon and martyr from Rome. According to tradition he was roasted alive on a gridiron because, when ordered to hand over the church's treasures, he presented the sick and poor. Due to the saint's popularity, the name came into general use in the Christian world (in various spellings). In the Middle Ages this name was common in England, partly because of a second saint by this name, a 7th-century archbishop of Canterbury. Likewise it has been common in Ireland due to the 12th-century Saint Laurence O'Toole (whose real name was Lorcán). Since the 19th century the spelling Lawrence has been more common, especially in America. A famous bearer was the British actor Laurence Olivier (1907-1989).",
    "M",
    "Lawrence, Larrie, Larry, Lawrie, Laz, Loren, Lars, Lorenzo",
    "LAWR-ents",
    379],
    ["Lee",
    "From a surname which was derived from Old English leah meaning 'clearing'. The surname belonged to Robert E. Lee (1807-1870), commander of the Confederate forces during the American Civil War. In his honour, it has been commonly used as a given name in the American South.",
    "M",
    "Leigh",
    "LEE",
    666],
    ["Leo",
    "Derived from Latin leo meaning 'lion', a cognate of LEON. It was popular among early Christians and was the name of 13 popes, including Saint Leo the Great who asserted the dominance of the Roman bishops (the popes) over all others in the 5th century. It was also borne by six Byzantine emperors and five Armenian kings. Another famous bearer was Leo Tolstoy (1828-1910), a Russian novelist whose works include 'War and Peace' and 'Anna Karenina'. Leo is also the name of a constellation and the fifth sign of the zodiac.",
    "M",
    "Leon, Levon, Lionel, Leone, Lev",
    "LE-o (German, Finnish), LAY-o (Dutch), LEE-o (English)",
    74],
    ["Levi",
    "Possibly means 'joined, attached' in Hebrew. As told in the Old Testament, Levi was the third son of Jacob and Leah, and the ancestor of one of the twelve tribes of the Israelites, known as the Levites. This was the tribe that formed the priestly class of the Israelites. The brothers Moses and Aaron were members. In the New Testament this is another name for the apostle Matthew. As an English Christian name, Levi came into use after the Protestant Reformation.",
    "M",
    "Lewi, Leevi, Leui",
    "LEE-vie (English), LE-vee (Dutch)",
    42],
    ["Louis",
    "French form of Ludovicus, the Latinized form of LUDWIG. This was the name of 18 kings of France, starting with Louis I the son of Charlemagne. Others include Louis IX (Saint Louis) who led two crusades and Louis XIV (called the Sun King) who was the ruler of France during the height of its power, the builder of the Palace of Versailles, and the longest reigning monarch in the history of Europe. It was also borne by kings of Germany (as Ludwig), Hungary (as Lajos), and other places. Apart from royalty, this name was only moderately popular in France during the Middle Ages. After the French Revolution, when Louis XVI was guillotined, it became less common. The Normans brought the name to England, where it was usually spelled Lewis, though the spelling Louis has been more common in America. Famous bearers include French scientist Louis Pasteur (1822-1895), Métis leader Louis Riel (1844-1885), who led a rebellion against Canada, Scottish author Robert Louis Stevenson (1850-1894), who wrote 'Treasure Island' and 'Dr Jekyll and Mr Hyde', and American jazz musician Louis Armstrong (1901-1971).",
    "M",
    "Ludovic, Lewis, Lou, Louie, Ludvig, Vico",
    "loo-EE (French), LOO-is (English)",
    289],
    ["Luke",
    "English form of the Greek name (Loukas) which meant 'from Lucania', Lucania being a region in southern Italy (of uncertain meaning). Luke was a doctor who travelled in the company of the apostle Paul. According to tradition, he was the author of the third gospel and Acts in the New Testament. He was probably of Greek ethnicity. He is considered a saint by many Christian denominations. Due to his renown, the name became common in the Christian world (in various spellings). As an English name, Luke has been in use since the 12th century alongside the Latin form Lucas. A famous fictional bearer was the hero Luke Skywalker from the 'Star Wars' movies, beginning in 1977.",
    "M",
    "Lucas, Lucky, Luka, Luca, Luc",
    "LOOK",
    29],
    ["Malcolm",
    "From Scottish Máel Coluim which means 'disciple of Saint COLUMBA'. This was the name of four kings of Scotland starting in the 10th century, including Malcolm III, who became king after killing Macbeth, the usurper who had murdered his father. The character Malcolm in Shakespeare's tragedy 'Macbeth' (1606) is based on him. Another famous bearer was Malcolm X (1925-1965), an American civil rights leader.",
    "M",
    "Malcom, Mael Coluim (Scottish)",
    "MAL-kem",
    410],
    ["Marcus",
    "Roman praenomen, or given name, which was probably derived from the name of the Roman god MARS. This was among the most popular of the Roman praenomina. Famous bearers include Marcus Tullius Cicero (known simply as Cicero), a 1st-century BC statesman and orator, Marcus Antonius (known as Mark Antony), a 1st-century BC politician, and Marcus Aurelius, a notable 2nd-century emperor. This was also the name of a pope of the 4th century. This spelling has occasionally been used in the English-speaking world, though the traditional English form Mark has been more common.",
    "M",
    "Mark, Markus, Marko, Marc, Marek, Margh, Marquihos, Markku",
    "MAR-kuws (Ancient Roman, Biblical Latin), MAHR-kes (English)",
    183],
    ["Maximilian",
    "From the Roman name Maximilianus, which was derived from MAXIMUS. It was borne by a 3rd-century saint and martyr. In the 15th century the Holy Roman Emperor Frederick III gave this name to his son and eventual heir. In this case it was a blend of the names of the Roman generals Fabius Maximus and Cornelius Scipio Aemilianus (see EMILIANO), who Frederick admired. It was subsequently borne by a second Holy Roman Emperor, two kings of Bavaria, and a short-lived Habsburg emperor of Mexico.",
    "M",
    "Max, Maxmilian, Miksa, Massimiliano",
    "mahk-see-MEE-lee-ahn (German), mak-si-MIL-ee-an (English)",
    432],
    ["Micah",
    "Contracted form of MICAIAH. Micah is one of the twelve minor prophets of the Old Testament. He authored the Book of Micah, which alternates between prophesies of doom and prophesies of restoration. It was occasionally used as an English given name by the Puritans after the Protestant Reformation, but it did not become common until the end of the 20th century.",
    "M",
    "Micaiah, Micajah, Mikhah",
    "MIE-ka",
    115],
    ["Moses",
    "From the Hebrew name (Mosheh) which is most likely derived from Egyptian mes meaning 'son', but could also possibly mean 'deliver' in Hebrew. The meaning suggested in the Old Testament of 'drew out' from Hebrew (mashah) is probably an invented etymology (see Exodus 2:10). The biblical Moses was drawn out of the Nile by the pharaoh's daughter and adopted into the royal family, at a time when the Israelites were slaves in Egypt. With his brother Aaron he demanded the pharaoh release the Israelites, which was only done after God sent ten plagues upon Egypt. Moses led the people across the Red Sea and to Mount Sinai, where he received the Ten Commandments from God. After 40 years of wandering in the desert the people reached Canaan, the Promised Land, but Moses died just before entering it.",
    "M",
    "Moshe, Mozes, Musa, Moisey, Mose",
    "MOZ-es",
    462],
    ["Nathan",
    "From the Hebrew name (Natan) meaning 'he gave'. In the Old Testament this is the name of a prophet during the reign of King David. He chastised David for his adultery with Bathsheba and for the death of Uriah the Hittite. Later he championed Solomon as David's successor. This was also the name of a son of David and Bathsheba. It has been used as a Christian given name in the English-speaking world since the Protestant Reformation. A famous bearer was Nathan Hale (1755-1776), an American spy executed by the British during the American Revolution.",
    "M",
    "Natan, Nosson, Nat, Nate, Natan",
    "NAY-than (English), na-TAWN (French)",
    43],
    ["Nicholas",
    "From the Greek name (Nikolaos) which meant 'victory of the people' from Greek (nike) 'victory' and (laos) 'people'. Saint Nicholas was a 4th-century bishop from Anatolia who, according to legend, saved the daughters of a poor man from lives of prostitution. He is the patron saint of children, sailors and merchants, as well as Greece and Russia. He formed the basis for the figure known as Santa Claus (created in the 19th century from Dutch Sinterklaas), the bringer of Christmas presents. Due to the renown of the saint, this name has been widely used in the Christian world. It has been common in England since the 12th century, though it became a bit less popular after the Protestant Reformation. The name has been borne by five popes and two czars of Russia.",
    "M",
    "Nic, Nick, Nicky, Nikolao, Nikolaj, Niko, Klaus, Mikolas, Miklos",
    "NIK-e-las (English), nee-ko-LAH (French)",
    63],
    ["Noah",
    "Derived from the Hebrew name (Noach) meaning 'rest, comfort'. According to the Old Testament, Noah was the builder of the Ark that allowed him, his family, and animals of each species to survive the great Flood. After the Flood he received the sign of the rainbow as a covenant from God. He was the father of Shem, Ham and Japheth. As an English Christian name, Noah has been used since the Protestant Reformation, being common among the Puritans. A famous bearer was the American lexicographer Noah Webster (1758-1843).",
    "M",
    "Noe, Nooa, Nojus, Noak",
    "NO-a",
    1],
    ["Norman",
    "From an old Germanic byname meaning 'northman', referring to a Viking. The Normans were Vikings who settled on the coast of France, in the region that became known as Normandy. In England the name Norman or Normant was used before the Norman conquest, first as a nickname for Scandinavian settlers and later as a given name. After the Conquest it became more common, but died out around the 14th century. It was revived in the 19th century, perhaps in part due to a character by this name in C. M. Yonge's novel 'The Daisy Chain' (1856).",
    "M",
    "Norm, Norma",
    "NAWR-man",
    942],
    ["Oliver",
    "From Olivier, a Norman French form of a Germanic name such as ALFHER or an Old Norse name such as Áleifr (see OLAF). The spelling was altered by association with Latin oliva 'olive tree'. In the Middle Ages the name became well-known in Western Europe because of the French epic 'La Chanson de Roland', in which Olivier was a friend and advisor of the hero Roland. In England Oliver was a common medieval name, however it became rare after the 17th century because of the military commander Oliver Cromwell, who ruled the country following the civil war. The name was revived in the 19th century, perhaps in part due to the title character in Charles Dickens' novel 'Oliver Twist' (1838), which was about a poor orphan living on the streets of London.",
    "M",
    "Oli, Ollie, Olivier, Oliviero, Oliwier",
    "AHL-a-ver (English), AW-lee-ver (German), O-lee-ver (Finnish)",
    12],
    ["Oscar",
    "Possibly means 'deer friend', derived from Gaelic os 'deer' and cara 'friend'. Alternatively, it may derive from the Old English name OSGAR or its Old Norse cognate ÁSGEIRR, which may have been brought to Ireland by Viking invaders and settlers. In Irish legend Oscar was the son of the poet Oisín and the grandson of the hero Fionn mac Cumhail. This name was popularized in continental Europe by the works of the 18th-century Scottish poet James Macpherson. Napoleon was an admirer of Macpherson, and he suggested Oscar as the second middle name of his godson, who eventually became king of Sweden as Oscar I. Another notable bearer was the Irish writer and humourist Oscar Wilde (1854-1900).",
    "M",
    "Oskar, Osku, Oszkar, Oskars",
    "AHS-ker",
    176],
    ["Oswald",
    "Derived from the Old English elements os 'god' and weald 'power, ruler'. Saint Oswald was a king of Northumbria who introduced Christianity to northeast England in the 7th century before being killed in battle. There was also an Old Norse cognate Ásvaldr in use in England, being borne by the 10th-century Saint Oswald of Worcester, who was of Danish ancestry. Though the name had died out by the end of the Middle Ages, it was revived in the 19th century.",
    "M",
    "Oz, Ozzie, Ozzy, Osvaldo, Ozbej",
    "AHZ-wawld (English), AWS-vahlt (German)",
    686],
    ["Owen",
    "Probably a Welsh form of EUGENE, though it might be derived from Welsh eoghunn meaning 'youth'. This was the name of several figures from Welsh history and mythology. In Arthurian legend Owain (also called Yvain in French sources) was one of the Knights of the Round Table, the son of King Urien and husband of the Lady of the Fountain. His character was based on that of Owain ap Urien, a 6th-century Welsh prince who fought against the Angles. This name was also borne by Owain Glyndwr, a 14th-century leader of Welsh resistance against English rule.",
    "M",
    "Owain, Ywain, Eugen, Yevhen, Evgeni",
    "O-en",
    23],
    ["Patrick",
    "From the Latin name Patricius, which meant 'nobleman'. This name was adopted in the 5th-century by Saint Patrick, whose birth name was Sucat. He was a Romanized Briton who was captured and enslaved in his youth by Irish raiders. After six years of servitude he escaped home, but he eventually became a bishop and went back to Ireland as a missionary. He is traditionally credited with Christianizing the island, and is regarded as Ireland's patron saint. In England and elsewhere in Europe during the Middle Ages this name was used in honour of the saint. However, it was not generally given in Ireland before the 17th century because it was considered too sacred for everyday use. It has since become very common there.",
    "M",
    "Padraig, Patrice, Paddy, Patsy, Pat, Patrik, Patricio, Patryk",
    "PAT-rik (English), pat-REEK (French), PAHT-rik (German)",
    170],
    ["Paul",
    "From the Roman family name Paulus, which meant 'small' or 'humble' in Latin. Paul was an important leader of the early Christian church. According to Acts in the New Testament, he was a Jewish Roman citizen who converted to Christianity after the resurrected Jesus appeared to him. After this he travelled the eastern Mediterranean as a missionary. His original Hebrew name was Saul. Many of the epistles in the New Testament were authored by him. Due to the renown of Saint Paul the name became common among early Christians. It was borne by a number of other early saints and six popes. In England it was relatively rare during the Middle Ages, but became more frequent beginning in the 17th century. A notable bearer was the American Revolutionary War figure Paul Revere (1735-1818), who warned of the advance of the British army. Famous bearers in the art world include the French impressionists Paul Cezanne (1839-1906) and Paul Gauguin (1848-1903), and the Swiss expressionist Paul Klee (1879-1940). It is borne by British musician Paul McCartney (1942-). This is also the name of the legendary American lumberjack Paul Bunyan.",
    "M",
    "Pauwel, Pal, Poul, Paulo, Pavel, Pasha, Pablo, Pau",
    "PAWL (English), POL (French), POWL (German)",
    206],
    ["Peter",
    "Derived from the Greek (Petros) meaning 'stone'. This is a translation used in most versions of the New Testament of the name Cephas, meaning 'stone' in Aramaic, which was given to the apostle Simon by Jesus (compare Matthew 16:18 and John 1:42). Simon Peter was the most prominent of the apostles during Jesus' ministry and is often considered the first pope. Due to the renown of the apostle, this name became common throughout the Christian world (in various spellings). In England the Normans introduced it in the Old French form Piers, which was gradually replaced by the spelling Peter starting in the 15th century. Besides the apostle, other saints by this name include the 11th-century reformer Saint Peter Damian and the 13th-century preacher Saint Peter Martyr. It was also borne by rulers of Aragon, Portugal, and Russia, including the Russian tsar Peter the Great (1672-1725), who defeated Sweden in the Great Northern War. Famous fictional bearers include Peter Rabbit from Beatrix Potter's children's books, and Peter Pan, the boy who refused to grow up in J. M. Barrie's 1904 play.",
    "M",
    "Piers, Petrus, Pieter, Peder, Pete, Pehr",
    "PEE-ter (English), PE-ter (German, Slovak), PAY-ter (Dutch)",
    207],
    ["Philip",
    "From the Greek name (Philippos) which means 'friend of horses', composed of the elements (philos) 'friend, lover' and (hippos) 'horse'. This was the name of five kings of Macedon, including Philip II the father of Alexander the Great. The name appears in the New Testament belonging to two people who are regarded as saints. First, one of the twelve apostles, and second, an early figure in the Christian church known as Philip the Deacon. This name was initially more common among Eastern Christians, though it came to the West by the Middle Ages. It was borne by six kings of France and five kings of Spain. It was regularly used in England during the Middle Ages, although the Spanish king Philip II, who attempted an invasion of England, helped make it less common by the 17th century. It was revived in the English-speaking world in the 19th century. Famous bearers include the Elizabethan courtier and poet Sir Philip Sidney (1554-1586) and the American science fiction novelist Philip K. Dick (1928-1982).",
    "M",
    "Filip, Phil, Pip, Flip, Philippe, Vilppu, Felipe",
    "FIL-ip (English), FEE-lip (Dutch)",
    433],
    ["Quentin",
    "French form of the Roman name QUINTINUS. It was borne by a 3rd-century saint, a missionary who was martyred in Gaul. The Normans introduced this name to England. In America it was brought to public attention by president Theodore Roosevelt's son Quentin Roosevelt (1897-1918), who was killed in World War I.",
    "M",
    "Quinten, Quintin, Quinton",
    "KWEN-tin",
    486],
    ["Ralph",
    "Contracted form of the Old Norse name RÁÐÚLFR (or its Norman form Radulf). Scandinavian settlers introduced it to England before the Norman conquest, though afterwards it was bolstered by Norman influence. In the Middle Ages it was usually spelled Ralf, but by the 17th century it was most commonly Rafe, reflecting the normal pronunciation. The Ralph spelling appeared in the 18th century. A famous bearer of the name was Ralph Waldo Emerson (1803-1882), an American poet and author who wrote on transcendentalism.",
    "M",
    "Rafe, Ralf, Raoul, Raul, Ralphie",
    "RALF (English), RAYF (English), RAHLF (German)",
    989],
    ["Raphael",
    "From the Hebrew name (Rafa'el) which meant 'God has healed'. In Hebrew tradition Raphael was the name of one of the seven archangels. He appears in the Book of Tobit, in which he disguises himself as a man named Azarias and accompanies Tobias on his journey to Media, aiding him along the way. In the end he cures Tobias's father Tobit of his blindness. He is not mentioned in the New Testament, though tradition identifies him with the angel troubling the water in John 5:4. This name has never been common in the English-speaking world, though it has been well-used elsewhere in Europe. A famous bearer was the 16th-century Renaissance master Raphael Sanzio (1483-1520), usually known simply as Raphael.",
    "M",
    "Rafael, Raf, Raph, Raffaelo, Rafal, Rafa",
    "ra-fa-EL (French), RAF-ee-el (English), RAY-fee-el (English)",
    533],
    ["Reynold",
    "From the Germanic name Raginald, composed of the elements ragin 'advice' and wald 'rule'. The Normans (who used forms like Reinald or Reinold) brought the name to Britain, where it reinforced rare Old English and Norse cognates already in existence. It was common during the Middle Ages, but became more rare after the 15th century.",
    "M",
    "Reginald, Reinhold, Ragnvald, Renaud, Ronaldo, Reynaldo",
    "REN-ald",
    453],
    ["Richard",
    "Means 'brave power', derived from the Germanic elements ric 'power, rule' and hard 'brave, hardy'. The Normans introduced this name to Britain, and it has been very common there since that time. It was borne by three kings of England including Richard I the Lionheart, one of the leaders of the Third Crusade in the 12th century. Famous bearers include two German opera composers, Richard Wagner (1813-1883) and Richard Strauss (1864-1949), as well as British explorer Sir Richard Burton (1821-1890), American physicist Richard Feynman (1918-1988) and American musician Little Richard.",
    "M",
    "Dick, Rich, Richie, Rick, Ricky, Ritchie, Ricard, Riku, Ricardo, Rico",
    "RICH-erd (English), ree-SHAHR (French), RIKH-ahrt (German)",
    160],
    ["Robert",
    "From the Germanic name Hrodebert meaning 'bright fame', derived from the Germanic elements hrod 'fame' and beraht 'bright'. The Normans introduced this name to Britain, where it replaced the Old English cognate Hreodbeorht. It has been a very common English name since that time. The name has been borne by two early kings of France, two Dukes of Normandy, and three kings of Scotland, including Robert the Bruce who restored the independence of Scotland from England in the 14th century. The author Robert Browning (1812-1889) and poets Robert Burns (1759-1796) and Robert Frost (1874-1963) are famous literary bearers of this name. Other bearers include Robert E. Lee (1807-1870), the commander of the Confederate army during the American Civil War, and American actors Robert Redford, Robert De Niro and Robert Downey Jr.",
    "M",
    "Rupert, Bob, Bobby, Rob, Robbie, Robin, Roberto, Rab",
    "RAH-bert (English), ro-BER (French), RO-bert (German), RAW-bert (Polish), RO-byert (Russian), RO-beert (Russian)",
    62],
    ["Roderick",
    "Means 'famous power' from the Germanic elements hrod 'fame' and ric 'power'. This name was in use among the Visigoths; it was borne by their last king (also known as Rodrigo), who died fighting the Muslim invaders of Spain in the 8th century. It also had cognates in Old Norse and West Germanic, and Scandinavian settlers and Normans introduced it to England, though it died out after the Middle Ages. It was revived in the English-speaking world by Sir Walter Scott's poem 'The Vision of Don Roderick' (1811).",
    "M",
    "Rod, Roddy, Hroderich, Rodrigo, Rory, Ruy",
    "RAHD-e-rik",
    733],
    ["Ryan",
    "From an Irish surname which was derived from Ó Riain meaning 'descendant of Rían'. The given name Rían probably means 'little king' (from Irish rí 'king' combined with a diminutive suffix).",
    "M",
    "Rian, Ry",
    "RIE-en",
    40],
    ["Samuel",
    "From the Hebrew name (Shemu'el) which could mean either 'name of God' or 'God has heard'. As told in the Books of Samuel in the Old Testament, Samuel was the last of the ruling judges. He led the Israelites during a period of domination by the Philistines, who were ultimately defeated in battle at Mizpah. Later he anointed Saul to be the first king of Israel, and even later anointed his successor David. As a Christian name, Samuel came into common use after the Protestant Reformation. Famous bearers include American inventor Samuel Morse (1791-1872), Irish writer Samuel Beckett (1906-1989), and American author Samuel Clemens (1835-1910), who wrote under the pen name Mark Twain.",
    "M",
    "Sam, Sammy, Samu, Samuil",
    "SAM-yoo-el (English), SAM-yel (English), sah-MWEL (Spanish), SAH-moo-el (Swedish, Finnish)",
    21],
    ["Scott",
    "From an English and Scottish surname which referred to a person from Scotland or a person who spoke Scottish Gaelic. It is derived from Latin Scoti meaning 'Gaelic speaker', with the ultimate origin uncertain.",
    "M",
    "Scot, Scottie, Scotty",
    "SKAHT",
    463],
    ["Shannon",
    "From the name of the River Shannon, the longest river in Ireland, called Abha na tSionainn in Irish. It is associated with the goddess Sionann and is sometimes said to be named for her. However it is more likely the goddess was named after the river, which may be related to Old Irish sen 'old, ancient'. As a given name, it first became common in America after the 1940s.",
    "M",
    "Shana, Shanna, Shannen, Shanon, Shannah",
    "SHAN-en",
    793],
    ["Silas",
    "Probably a short form of SILVANUS. This is the name of a companion of Saint Paul in the New Testament. Paul refers to him as Silvanus in his epistles, though it is possible that Silas was in fact a Greek form of the Hebrew name SAUL (via Aramaic). As an English name it was not used until after the Protestant Reformation. It was utilized by George Eliot for the title character in her novel 'Silas Marner' (1861).",
    "M",
    "Silvanus, Sylvain, Silvano",
    "SIE-les",
    119],
    ["Simon",
    "From (Simon), the New Testament Greek form of the Hebrew name (Shim'on) which meant 'he has heard'. This name is spelled Simeon, based on Greek Συμεων, in many translations of the Old Testament, where it is borne by the second son of Jacob. In the New Testament Simon is the name of several characters, including the man who carried the cross for Jesus. Most importantly however it was borne by the leading apostle Simon, also known as Peter (a name given to him by Jesus). Because of the apostle, this name has been common in the Christian world. In England it was popular during the Middle Ages, though it became rarer after the Protestant Reformation.",
    "M",
    "Siemen, Symeon, Simo, Semyon, Jimeno, Siem",
    "SIE-men (English), see-MAWN (French), ZEE-mawn (German), SEE-mawn (Dutch)",
    243],
    ["Solomon",
    "From the Hebrew name (Shelomoh) which was derived from Hebrew (shalom) 'peace'. As told in the Old Testament, Solomon was a king of Israel, the son of David and Bathsheba. He was renowned for his wisdom and wealth. Towards the end of his reign he angered God by turning to idolatry. Supposedly, he was the author of the Book of Proverbs, Ecclesiastes and the Song of Solomon. This name has never been overly common in the Christian world, and it is considered typically Jewish. It was however borne by an 11th-century Hungarian king.",
    "M",
    "Sol, Saul, Suleiman, Suljo, Salomao, Shelomoh",
    "SAHL-e-men",
    369],
    ["Stephen",
    "From the Greek name (Stephanos) meaning 'crown', more precisely 'that which surrounds'. Saint Stephen was a deacon who was stoned to death, as told in Acts in the New Testament. He is regarded as the first Christian martyr. Due to him, the name became common in the Christian world. It was popularized in England by the Normans. This was the name of kings of England, Serbia, and Poland, as well as ten popes. It was also borne by the first Christian king of Hungary (10th century), who is regarded as the patron saint of that country. More recent bearers include British physicist Stephen Hawking and the American author Stephen King.",
    "M",
    "Steven, Steve, Stevie, Stephanos, Stefan, Esteban, Stipe",
    "STEEV-ən (English), STEF-ən (English)",
    265],
    ["Terrance",
    "From the Roman family name Terentius which is of unknown meaning. Famous bearers include Publius Terentius Afer, a Roman playwright, and Marcus Terentius Varro, a Roman scholar. It was also borne by several early saints. The name was used in Ireland as an Anglicized form of TOIRDHEALBHACH, but it was not in use as an English name until the late 19th century.",
    "M",
    "Terry, Ter, Terenti, Terenzio, Terentiy",
    "TER-ents",
    840],
    ["Theodore",
    "From the Greek name (Theodoros), which meant 'gift of god' from Greek θεος (theos) 'god' and (doron) 'gift'. This was the name of several saints, including Theodore of Amasea, a 4th-century Greek soldier; Theodore of Tarsus, a 7th-century archbishop of Canterbury; and Theodore the Studite, a 9th-century Byzantine monk. It was also borne by two popes. This was a common name in classical Greece, and, due to both the saints who carried it and the favourable meaning, it came into general use in the Christian world, being especially popular among Eastern Christians. It was however rare in Britain before the 19th century. Famous bearers include three tsars of Russia (in the Russian form Fyodor) and American president Theodore Roosevelt (1858-1919).",
    "M",
    "Ted, Teddy, Theo, Toros, Teo, Fedor, Teodoro",
    "THEE-e-dawr",
    83],
    ["Thomas",
    "Greek form of the Aramaic name (Ta'oma') which meant 'twin'. In the New Testament this is the name of an apostle. When he heard that Jesus had risen from the dead he initially doubted the story, until Jesus appeared before him and he examined his wounds himself. According to tradition he was martyred in India. Due to his renown, the name came into general use in the Christian world. In England the name was introduced by the Normans and became very popular due to Saint Thomas Becket, a 12th-century archbishop of Canterbury and martyr. Another notable saint by this name was the 13th-century Italian philosopher and theologian Thomas Aquinas, who is regarded as a Doctor of the Church. Other famous bearers include philosopher Thomas Hobbes (1588-1679), American president Thomas Jefferson (1743-1826), novelist Thomas Hardy (1840-1928), and inventor Thomas Edison (1847-1931).",
    "M",
    "Tomas, Tom, Tommie, Tommy, Tuomo, Tommaso, Tomek, Tam",
    "TAHM-es (English), TOM-es (English), to-MAH (French), TO-mahs (German, Dutch), tho-MAHS (Greek)",
    48],
    ["Tristan",
    "Old French form of the Pictish name Drustan, a diminutive of DRUST. The spelling was altered by association with Latin tristis 'sad'. Tristan is a character in medieval French tales, probably inspired by older Celtic legends, and ultimately merged into Arthurian legend. According to the story Tristan was sent to Ireland in order to fetch Isolde, who was to be the bride of King Mark of Cornwall. On the way back, Tristan and Isolde accidentally drink a potion which makes them fall in love. Their tragic story was very popular in the Middle Ages, and the name has occasionally been used since that time.",
    "M",
    "Drystan, Tristram, Tristao",
    "TRIS-ten (English), trees-TAWN (French)",
    108],
    ["Tyrone",
    "From the name of a county in Northern Ireland which is derived from Irish Gaelic Tir Eoghain meaning 'land of EOGHAN'. This name was popularized by American actor Tyrone Power (1914-1958), who was named after his great-grandfather, an Irish actor.",
    "M",
    "Ty, Tyron, Taryn",
    "tie-RON",
    939],
    ["Ulysses",
    "Latin form of ODYSSEUS. It was borne by Ulysses S. Grant (1822-1885), the commander of the Union forces during the American Civil War, who went on to become an American president. Irish author James Joyce used it as the title of his book 'Ulysses' (1920), which loosely parallels Homer's epic the 'Odyssey'.",
    "M",
    "Ulysse, Odysseus, Ulisse, Ulises",
    "yoo-LIS-eez",
    1692],
    ["Valentin",
    "From the Roman cognomen Valentinus which was itself from the name Valens meaning 'strong, vigourous, healthy' in Latin. Saint Valentine was a 3rd-century martyr. His feast day was the same as the Roman fertility festival of Lupercalia, which resulted in the association between Valentine's day and love. As an English name, it has been used occasionally since the 12th century.",
    "M",
    "Val, Valentinus, Tino, Vali, Walenty, Valentijn",
    "VAL-en-tien",
    1445],
    ["Victor",
    "Roman name meaning 'victor, conqueror' in Latin. It was common among early Christians, and was borne by several early saints and three popes. It was rare as an English name during the Middle Ages, but it was revived in the 19th century. A famous bearer was the French writer Victor Hugo (1802-1885), who authored 'The Hunchback of Notre Dame' and 'Les Misérables'.",
    "M",
    "Vitor, Bittor, Vittore, Wiktor, Vitya, Gwythyr",
    "VIK-ter (English), veek-TOR (French)",
    164],
    ["Vincent",
    "From the Roman name Vincentius, which was from Latin vincere 'to conquer'. This name was popular among early Christians, and it was borne by many saints. As an English name, Vincent has been in use since the Middle Ages, though it did not become common until the 19th century. Famous bearers include the French priest Saint Vincent de Paul (1581-1660) and the post-impressionist painter Vincent van Gogh (1853-1890).",
    "M",
    "Vin, Vince, Vinnie, Vinny, Vincenzo, Enzo, Vikenti, Vicente",
    "VIN-sent",
    104],
    ["Walter",
    "From a Germanic name meaning 'ruler of the army', composed of the elements wald 'rule' and hari 'army'. The Normans brought it to England, where it replaced the Old English cognate Wealdhere. A famous bearer of the name was Sir Walter Scott (1771-1832), a Scottish novelist who wrote 'Ivanhoe' and other notable works.",
    "M",
    "Valter, Wahldar, Wally, Walt, Gauthier, Bhaltair, Gualterio",
    "WAWL-ter (English), VAHL-ter (German, Polish, Italian)",
    301],
    ["Wesley",
    "From a surname which was derived from a place name meaning 'west meadow' in Old English. It has been sometimes given in honour of John Wesley (1703-1791), the founder of Methodism.",
    "M",
    "Wes",
    "WES-lee",
    117],
    ["William",
    "From the Germanic name Willahelm, which was composed of the elements wil 'will, desire' and helm 'helmet, protection'. Saint William of Gellone was an 8th-century cousin of Charlemagne who became a monk. The name was common among the Normans, and it became extremely popular in England after William the Conqueror was recognized as the first Norman king of England in the 11th century. It was later borne by three other English kings, as well as rulers of Scotland, Sicily (of Norman origin), the Netherlands and Prussia. Other famous bearers include William Wallace, a 13th-century Scottish hero, and William Tell, a legendary 14th-century Swiss hero. In the literary world it was borne by dramatist William Shakespeare (1564-1616), poet William Blake (1757-1827), poet William Wordsworth (1770-1850), dramatist William Butler Yeats (1865-1939), author William Faulkner (1897-1962), and author William S. Burroughs (1914-1997).",
    "M",
    "Bill, Billie, Billy, Liam, Will, Willy, Wilhelm, Vili, Guillaume, Guillermo, Ville",
    "WIL-ee-em, WIL-yem",
    3],
    ["Xavier",
    "Derived from the Basque place name Etxeberria meaning 'the new house'. This was the surname of the Jesuit priest Saint Francis Xavier (1506-1552) who was borne in a village of this name. He was a missionary to India, Japan, China, and other areas in East Asia, and he is the patron saint of the Orient and missionaries. His surname has since been adopted as a given name in his honour, chiefly among Catholics.",
    "M",
    "Zavier, Javier, Xabi, Saverio, Ksawery",
    "ZAY-vee-er (English), ZAY-vyer (English), ig-ZAY-vee-er (English), za-VYE (French), sha-VYER (Portuguese)",
    88],
    ["Zachary",
    "Usual English form of ZACHARIAS, used in some English versions of the New Testament. This form has been in use since the Middle Ages, though it did not become common until after the Protestant Reformation. It was borne by American military commander and president Zachary Taylor (1784-1850).",
    "M",
    "Zac, Zach, Zakaria, Zekharyah, Saku, Zakhar, Zekeriya",
    "ZAK-a-ree",
    90],
    ["Zane",
    "From an English surname of unknown meaning. It was introduced as a given name by American author Zane Grey (1872-1939). Zane was in fact his middle name - it had been his mother's maiden name.",
    "M",
    "Zayn",
    "ZAYN",
    211],
    ["Aaliyah",
    "Feminine form of AALI. It was popularized in the English-speaking world by the singer Aaliyah Haughton (1979-2001), who was known simply as Aaliyah.",
    "F",
    "Aleah, Alea, Aliah",
    "a-LEE-a",
    53],
    ["Abigail",
    "From the Hebrew name ('Avigayil) meaning 'my father is joy'. In the Old Testament this is the name of Nabal's wife. After Nabal's death she became the third wife of King David. As an English name, Abigail first became common after the Protestant Reformation, and it was popular among the Puritans. The biblical Abigil refers to herself as a servant, and beginning in the 17th century the name became a slang term for a servant, especially after the release of the play 'The Scornful Lady' (1616) which featured a character named Abigail. The name went out of fashion at that point, but it was revived in the 20th century.",
    "F",
    "Abbey, Abby, Gail, Gayle, Gaila",
    "AB-i-gayl (English), AH-bee-giel (German)",
    8],
    ["Alexandra",
    "Feminine form of ALEXANDER. In Greek mythology this was a Mycenaean epithet of the goddess Hera, and an alternate name of Cassandra. It was borne by several early Christian saints, and also by the wife of Nicholas II, the last czar of Russia. She was from Germany and had the birth name Alix, but was renamed Александра (Aleksandra) upon joining the Russian Church.",
    "F",
    "Alexandria, Alejandra, Alessandra, Oleksandra, Alex, Lexi, Sandy, Zandra, Alyx, Alessa",
    "al-eg-ZAN-dra (English), ah-lek-SAHN-drah (German, Italian), ah-lek-SAHN-drah (Dutch)",
    110],
    ["Amanda",
    "In part this is a feminine form of AMANDUS. However, it was not used during the Middle Ages. In the 17th century it was recreated by authors and poets who based it directly on Latin amanda 'lovable, worthy of love'. Notably, the playwright Colley Cibber used it for a character in his play 'Love's Last Shift' (1696). It came into regular use during the 19th century.",
    "F",
    "Mandi, Mandy, Amando, Amandine",
    "a-MAN-da (English), ah-MAHN-dah (Spanish, Italian, German)",
    329],
    ["Anna",
    "Form of Channah (see HANNAH) used in the Greek and Latin Old Testament. Many later Old Testament translations, including the English, use the Hannah spelling instead of Anna. The name appears briefly in the New Testament belonging to a prophetess who recognized Jesus as the Messiah. It was a popular name in the Byzantine Empire from an early date, and in the Middle Ages it became common among Western Christians due to veneration of Saint Anna (usually known as Saint Anne in English), the name traditionally assigned to the mother of the Virgin Mary. In the English-speaking world, this form came into general use in the 18th century, joining Ann and Anne. The name was borne by several Russian royals, including an 18th-century empress of Russia. It is also the name of the main character in Leo Tolstoy's novel 'Anna Karenina' (1877), about a married aristocrat who begins an ultimately tragic relationship with Count Vronsky.",
    "F",
    "Anissa, Anne, Keanna, Annetta, Anika, Anya, Anka, Annabelle, Antje",
    "AN-a (English), AHN-nah (Italian, Dutch, Norwegian, Polish), AH-nah (German, Russian), AN-nah (Danish)",
    51],
    ["Ariel",
    "Means 'lion of God' in Hebrew. In the Old Testament it is used as another name for the city of Jerusalem. Shakespeare used it as the name of a spirit in his play 'The Tempest' (1611), and one of the moons of Uranus bears this name in his honour. As an English name, it became more common for females in the 1980s, especially after it was used for the title character in the Walt Disney film 'The Little Mermaid' (1989).",
    "F",
    "Ariella, Arielle, Ari",
    "AR-ee-el, ER-ee-el, AY-ree-el",
    140],
    ["Ashley",
    "From an English surname which was originally derived from place names meaning 'ash tree clearing', from a combination of Old English ash and leah. Until the 1960s it was more commonly given to boys in the United States, but it is now most often used on girls.",
    "F",
    "Ashlea, Ashlee, Ashleigh, Ashlie, Ashlyn, Ashlynn",
    "ASH-lee",
    101],
    ["Avery",
    "From a surname which was itself derived from the Norman French form of the given names ALBERICH or ALFRED.",
    "F",
    "Ava, Avy",
    "AY-ver-ee, AYV-ree",
    16],
    ["Barbara",
    "Derived from Greek (barbaros) meaning 'foreign'. According to legend, Saint Barbara was a young woman killed by her father Dioscorus, who was then killed by a bolt of lightning. She is the patron of architects, geologists, stonemasons and artillerymen. Because of her renown, the name came into general use in the Christian world in the Middle Ages. In England it became rare after the Protestant Reformation, but it was revived in the 19th century.",
    "F",
    "Babs, Barb, Barbie, Varya, Barbra",
    "BAHR-ber-a (English), BAHR-bra (English), BAHR-bah-rah (German), bahr-BAH-rah (Polish) ",
    856]]

    baby_names.each do |name, meaning, gender, related, pronounced, popularity|

      Baby.new(name: name, meaning: meaning, gender: gender,
               related: related, pronounced: pronounced,
               popularity: popularity).save(validate: false)
    end


# female_names =
#   [["Canada Drives",
#     "Suite 600, Two Bentall Centre 555 Burrard Street, Vancouver, BC V7X 1M8",
#     "Facilitates auto financing for consumers through an online portal",
#     100, 20, "https://www.canadadrives.ca/",
#     "https://twitter.com/canadadrives"],
#   ]
